"""Prepare durable files and supervised controls after every computer resume."""
import ast,os,sys,json,base64,pathlib,subprocess,socket,time,signal,urllib.request,shlex,re
base=pathlib.Path.home()/'tameduck';base.mkdir(parents=True,exist_ok=True)
profile=base/'chrome';profile.mkdir(exist_ok=True)
(base/'driver.py').write_bytes(base64.b64decode(sys.argv[1]))
env={**os.environ,'DISPLAY':':0','XDG_RUNTIME_DIR':'/run/user/'+str(os.getuid()),'DBUS_SESSION_BUS_ADDRESS':'unix:path=/run/user/'+str(os.getuid())+'/bus'}
# Disable the input method for our browser and control subprocesses: bursts
# of remote keystrokes can overflow its queue. Leave the desktop daemon alive;
# its window manager may still have an XIM connection to it (see below).
env.update(GTK_IM_MODULE='none',QT_IM_MODULE='none',XMODIFIERS='@im=none')
def ensure_display():
 # A restored provider snapshot can leave LightDM stopped while cua-driver waits for X.
 # Start only a stopped display; never restart a running or externally managed desktop.
 state=subprocess.run(['systemctl','is-active','display-manager.service'],capture_output=True,text=True,timeout=5).stdout.strip()
 if state in ('inactive','failed') and not pathlib.Path('/tmp/.X11-unix/X0').exists():
  subprocess.run(['sudo','-n','systemctl','start','--no-block','display-manager.service'],check=True,timeout=5)
ensure_display()
# Provider API readiness precedes Xorg and can precede its final driver restart.
# A screen-ready daemon must be stable before creating our MCP transport. A
# restored service can also remain active after its runtime socket disappeared:
# systemd then has nothing to restart and every later bootstrap waits on a path
# that can never return. Once X itself answers and the daemon has been stable
# for five seconds, repair that exact state once. Human control prevents this
# script from running, so it cannot interrupt somebody holding the screen.
def wait_for_provider_driver(seconds=12):
 deadline=time.monotonic()+seconds;repaired=False
 while time.monotonic()<deadline:
  stable=x_ready=driver_socket=False
  try:
   raw=subprocess.check_output(['systemctl','--user','show','cua-driver.service','-p','ActiveState','-p','ActiveEnterTimestampMonotonic'],env=env,timeout=2,text=True)
   state=dict(line.split('=',1) for line in raw.splitlines() if '=' in line)
   age=time.monotonic()-int(state.get('ActiveEnterTimestampMonotonic','0'))/1000000
   stable=state.get('ActiveState')=='active' and age>=5
   driver_socket=pathlib.Path('/run/ascii-cua/driver.sock').exists()
   subprocess.run(['xset','q'],env={**env,'XAUTHORITY':str(pathlib.Path.home()/'.Xauthority')},check=True,timeout=2,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
   x_ready=True
  except (OSError,ValueError,subprocess.SubprocessError):pass
  if stable and driver_socket and x_ready:return True
  if stable and x_ready and not driver_socket and not repaired:
   subprocess.run(['systemctl','--user','restart','--no-block','cua-driver.service'],env=env,check=True,timeout=5,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
   repaired=True
  time.sleep(.5)
 return False
if not wait_for_provider_driver():
 if len(sys.argv)<3:raise RuntimeError('Desktop is still starting; retry computer_start.')
 print('TAMEDUCK_DESKTOP_STARTING',flush=True);sys.exit(0)
# Keep the desktop input method alive. Openbox retains an XIM connection to
# ibus; stopping that server can block a later keyboard reload while Openbox
# holds a synchronous mouse grab. Its frozen grab prevents clicks reaching
# the browser even though the remote input transport delivered them.
# Remove only the exact autostart files generated by older bootstrap versions;
# never delete a user's custom file with the same name.
autostart=pathlib.Path.home()/'.config/autostart'
old_override='[Desktop Entry]\nType=Application\nName={name}\nExec=/bin/true\nHidden=true\nX-GNOME-Autostart-enabled=false\n'
for entry in ['im-launch.desktop','ibus.desktop','ibus-autostart.desktop']:
 path=autostart/entry
 try:
  if path.read_text()==old_override.format(name=entry[:-8]): path.unlink()
 except (FileNotFoundError,OSError,UnicodeError): pass
# The person driving this screen is somewhere else, on their own machine, and
# their modifier keys arrive here as whatever the remote viewer maps them to. A
# Mac's Command key arrives as Super - so Cmd+H, which on a Mac means "hide this
# app" and is pure muscle memory, arrives as Super+H and the window manager
# minimises the browser. Everything vanishes and the desktop is all that is
# left, with nothing on screen to explain it. A lone Cmd press is worse: mutter
# treats a bare Super as the overlay key and opens the menu over the work.
#
# None of these bindings are any use to somebody on the far end of a video
# stream - they cannot see a workspace switcher, and they have their own window
# manager already. So the desktop stops claiming the modifier, and a stray Cmd
# does nothing instead of throwing the session away. Alt+Tab is left alone.
runtime=os.environ.get('XDG_RUNTIME_DIR') or '/run/user/%d'%os.getuid()
settings=dict(env,XDG_RUNTIME_DIR=runtime,DBUS_SESSION_BUS_ADDRESS='unix:path='+runtime+'/bus')
def desktop_setting(schema,key,value):
 try:subprocess.run(['gsettings','set',schema,key,value],env=settings,timeout=5,check=False,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 except Exception:pass
desktop_setting('org.gnome.mutter','overlay-key','')
# Every binding that claims Super, from every schema on the machine. Naming the
# schemas was the same mistake as naming the keys, one level up: this listed
# four and the three that actually bit somebody were in none of them. This image
# carries pieces of several desktops, and the shortcut that threw a person's
# work away was org.cinnamon.desktop.keybindings.wm show-desktop, with Budgie's
# own toggle-raven and toggle-notifications beside it. Ask the machine what it
# has rather than guessing which desktop it thinks it is.
try:listing=subprocess.run(['gsettings','list-recursively'],env=settings,timeout=20,capture_output=True,text=True).stdout
except Exception:listing=''
for line in listing.splitlines():
 parts=line.split(' ',2)
 if len(parts)!=3:continue
 schema,key,raw=parts
 if '<super>' not in raw.lower():continue
 # Take out the Super entries and put the rest back, rather than emptying the
 # key. Emptying it is why Alt+Tab disappeared along with Super+Tab: they are
 # two entries of one setting, and only one of them is the problem.
 if raw.startswith('['):
  try:values=ast.literal_eval(raw)
  except Exception:continue
  if not isinstance(values,list):continue
  rest=[v for v in values if '<super>' not in str(v).lower()]
  if len(rest)!=len(values):desktop_setting(schema,key,'['+', '.join("'"+str(v)+"'" for v in rest)+']')
 # Some are a single string rather than a list, and those have no other entry
 # to preserve, so they simply go.
 elif raw.startswith("'"):desktop_setting(schema,key,'')
# Not a shortcut, and the one that is hardest to explain when it happens:
# holding this modifier and dragging anywhere in a window moves the whole
# window. A Mac user holding Cmd to click something drags the browser across
# the desktop instead. Alt is the traditional alternative and collides with
# nothing a remote viewer sends by accident.
desktop_setting('org.gnome.desktop.wm.preferences','mouse-button-modifier','<Alt>')
units=pathlib.Path.home()/'.config/systemd/user';units.mkdir(parents=True,exist_ok=True)
unit='[Unit]\nDescription=TameDuck desktop controls\n[Service]\nType=simple\nExecStart='+str(base/'venv/bin/python')+' '+str(base/'driver.py')+' --serve\nRestart=always\nRestartSec=1\nTimeoutStopSec=2s\nTimeoutStartSec=5s\nKillMode=control-group\n'
(units/'tameduck-control.service').write_text(unit)
print('Restarting desktop controls',flush=True)
# Start explicitly once the provider is ready; do not join its desktop boot target.
subprocess.run(['systemctl','--user','disable','tameduck-control.service'],env=env,timeout=5,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
subprocess.run(['systemctl','--user','daemon-reload'],env=env,check=True,timeout=5,stdout=subprocess.DEVNULL)
subprocess.run(['systemctl','--user','stop','tameduck-control.service'],env=env,timeout=5,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
# Retire pre-service helpers; their transport leases cannot be reused after a snapshot.
for item in pathlib.Path('/proc').glob('[0-9]*/cmdline'):
 try:
  args=item.read_bytes().split(bytes([0]))
  if str(base/'driver.py').encode() in args and b'--serve' in args:os.kill(int(item.parent.name),signal.SIGKILL)
 except (OSError,ValueError):pass
subprocess.run(['systemctl','--user','reset-failed','tameduck-control.service'],env=env,timeout=3,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
subprocess.run(['systemctl','--user','start','--no-block','tameduck-control.service'],env=env,check=True,timeout=5,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
# Ten seconds was not enough. This waits on two separate things - our own
# controls answering a ping, and the provider's driver socket existing - and on
# a machine that has just booted, or a busy one, either can still be coming up.
# Somebody who pressed Take control a moment after starting a computer got
# "The computer action could not finish", with nothing said about what was slow,
# and the fix was to try again later. Wait long enough to cover a cold start,
# and say which half was missing when it really does not arrive.
ours=theirs=False
# Shorter than the budget the host gives this whole script, deliberately, and
# the two must stay that way round. It was the same 45 seconds as the host's,
# so the moment this gave up was the moment the host stopped listening: the
# message below - the only one that says which half of the desktop failed to
# start - could never once be delivered, and every failure here arrived as a
# bare timeout instead. tests/computer-stop.test.mjs holds the two numbers to
# their order.
deadline=time.monotonic()+30
# The provider's daemon can lose its socket and keep running (see driver.py).
# Waiting out the thirty seconds for a file that was not coming back failed the
# setup of new computers on the provider's image of 23 September; restarting
# the daemon brings it back.
missing=None;repairs=0
while time.monotonic()<deadline:
 try:
  with socket.socket(socket.AF_UNIX) as s:
   s.settimeout(.5);s.connect(str(base/'control.sock'));s.sendall(b'{"ping":true}\n');assert b'ready' in s.recv(100)
  ours=True
 except (OSError,AssertionError):ours=False
 theirs=pathlib.Path('/run/ascii-cua/driver.sock').exists()
 if ours and theirs:break
 if theirs:missing=None
 elif missing is None:missing=time.monotonic()
 elif time.monotonic()-missing>3 and repairs<2:
  subprocess.run(['systemctl','--user','restart','--no-block','cua-driver.service'],env=env,timeout=5,check=False,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  missing=None;repairs+=1
 time.sleep(.25)
else:raise RuntimeError('Desktop control service did not start: '+('the desktop provider'+(' and TameDuck controls' if not ours else '')+' had not finished starting' if not theirs else 'TameDuck controls did not answer'))
# Browser windows restart; the saved profile and session files remain on disk.
argument=('--user-data-dir='+str(profile)).encode();found=False
for item in pathlib.Path('/proc').glob('[0-9]*/cmdline'):
 try:
  parts=shlex.split(item.read_bytes().replace(bytes([0]),b' ').decode())
  if argument.decode() in parts and not any(a.startswith('--type=') for a in parts):found=True
 except (OSError,ValueError):pass
# Respect the browser's saved language; provider launch defaults otherwise force English.
prefs_path=profile/'Default/Preferences'
try:prefs=json.loads(prefs_path.read_text())
except (OSError,ValueError):prefs={}
try:browser_settings=json.loads((base/'browser-settings.json').read_text())
except (OSError,ValueError):browser_settings={}
intl=prefs.get('intl',{})
language=browser_settings.get('language') or (intl.get('selected_languages') or intl.get('accept_languages') or '').split(',')[0]
if not isinstance(language,str) or not re.fullmatch(r'[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*',language):language=''
language_flags=['--lang='+language,'--fingerprint-locale='+language] if language else []
rewrite_prefs=False
if language:
 env.update(LANG=language.replace('-','_')+'.UTF-8',LANGUAGE=language.replace('-','_'))
 if not found and browser_settings.get('language'):
  languages=list(dict.fromkeys([language,language.split('-')[0],'en-US','en']))
  prefs.setdefault('intl',{}).update(accept_languages=','.join(languages),selected_languages=','.join(languages))
  rewrite_prefs=True
# Stopping the computer is how this product saves a machine, and it stops with
# the browser still running, so Chrome finds its profile marked crashed every
# single time it comes back and puts a "Restore pages?" bubble over the duck's
# screen. It sits in every screenshot anybody looks at, and it holds the
# keyboard: the first thing typed after a resume goes into its Restore button
# instead of the page, and nothing on the screen explains why. We put the tabs
# back ourselves from browser-tabs.json, so there is nothing for that bubble to
# offer. Tell Chrome what is true from its point of view: the profile closed.
if not found:
 prefs.setdefault('profile',{}).update(exit_type='Normal',exited_cleanly=True)
 rewrite_prefs=True
if rewrite_prefs:
 prefs_path.parent.mkdir(parents=True,exist_ok=True)
 prefs_path.write_text(json.dumps(prefs))
saved_urls=[]
try:
 saved_urls=[u for u in json.loads((base/'browser-tabs.json').read_text()).get('urls',[]) if isinstance(u,str) and u.startswith(('http://','https://'))][:30]
except (OSError,ValueError):pass
if saved_urls and not found:(base/'browser-restoring').touch()
if not found:
 for name in ['SingletonLock','SingletonSocket','SingletonCookie']:
  try:(profile/name).unlink()
  except FileNotFoundError:pass
 log=open(base/'chrome.log','ab')
 # The service needs the user bus for desktop controls, but forcing that bus
 # onto Chrome makes accepted native key events have no effect. Let Chrome
 # discover the desktop session bus itself.
 browser_env={key:value for key,value in env.items() if key!='DBUS_SESSION_BUS_ADDRESS'}
 subprocess.Popen(['google-chrome-stable','--no-first-run','--start-maximized','--disable-session-crashed-bubble',argument.decode(),'--remote-debugging-address=127.0.0.1','--remote-debugging-port=9223']+language_flags+(saved_urls or ['--restore-last-session']),env=browser_env,stdin=subprocess.DEVNULL,stdout=log,stderr=log,start_new_session=True)
if saved_urls and not found:
 # Restore only a browser we started. An existing native browser may have no
 # debugging port; its live tabs must not block desktop readiness or be reopened.
 restored=False
 for attempt in range(15):
  try:
   with urllib.request.urlopen('http://127.0.0.1:9223/json/list',timeout=1) as response:tabs=json.load(response)
   if any(t.get('type')=='page' and t.get('url','').startswith(('http://','https://')) for t in tabs):restored=True;break
  except (OSError,ValueError):pass
  time.sleep(.5)
 if not restored:
  print('TAMEDUCK_DESKTOP_STARTING',flush=True);sys.exit(0)
apps=pathlib.Path.home()/'.local/share/applications';apps.mkdir(parents=True,exist_ok=True)
(apps/'tameduck-browser.desktop').write_text('[Desktop Entry]\nType=Application\nName=TameDuck Browser\nExec=env -u DBUS_SESSION_BUS_ADDRESS GTK_IM_MODULE=none QT_IM_MODULE=none XMODIFIERS=@im=none google-chrome-stable --user-data-dir='+str(profile)+' --start-maximized --restore-last-session %U\nMimeType=text/html;x-scheme-handler/http;x-scheme-handler/https;\n')
try:subprocess.run(['xdg-settings','set','default-web-browser','tameduck-browser.desktop'],env=env,timeout=3,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
except subprocess.TimeoutExpired:pass
print('Desktop workspace ready')
