// Curated from provider-owned documentation, reviewed 2026-09-16.
// Keep auth hosts explicit: discovery must never send credentials to arbitrary hosts.
export const mcpCatalog = [
  {
    id: "github",
    name: "GitHub",
    monogram: "GH",
    color: "#24292f",
    category: "Development",
    description: "Repositories, pull requests, issues, and code review.",
    url: "https://api.githubcopilot.com/mcp/",
    auth: ["secret"],
    keyLabel: "GitHub personal access token",
    keyHint:
      "Choose a fine-grained token with access to the repositories and permissions your ducks need.",
    docs: "https://github.com/github/github-mcp-server",
    keyUrl: "https://github.com/settings/personal-access-tokens",
  },
  {
    id: "notion",
    name: "Notion",
    monogram: "N",
    color: "#171717",
    category: "Work & knowledge",
    description:
      "Search your knowledge base and work with pages and databases.",
    url: "https://mcp.notion.com/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.notion.com"],
    docs: "https://developers.notion.com/guides/mcp/get-started-with-mcp",
  },
  {
    id: "linear",
    name: "Linear",
    monogram: "L",
    color: "#5146ce",
    category: "Work & knowledge",
    description: "Plan projects, track issues, and keep work moving.",
    url: "https://mcp.linear.app/mcp",
    auth: ["oauth", "secret"],
    oauthHosts: ["mcp.linear.app"],
    scope: "read write",
    keyLabel: "Linear API key",
    docs: "https://linear.app/docs/mcp",
    keyUrl: "https://linear.app/settings/api",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    monogram: "A",
    color: "#0757d6",
    category: "Work & knowledge",
    description: "Jira issues, Confluence knowledge, and your Atlassian tools.",
    url: "https://mcp.atlassian.com/v2/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.atlassian.com", "auth.atlassian.com"],
    hint: "Your Atlassian administrator may need to allow this installation's domain in Rovo MCP settings.",
    docs: "https://atlassian.github.io/atlassian-mcp-server/",
  },
  {
    id: "stripe",
    name: "Stripe",
    monogram: "S",
    color: "#635bda",
    category: "Business",
    description: "Customers, subscriptions, invoices, and payment operations.",
    url: "https://mcp.stripe.com",
    auth: ["oauth", "secret"],
    oauthHosts: ["mcp.stripe.com", "access.stripe.com"],
    keyLabel: "Stripe restricted API key",
    keyHint:
      "Use a restricted key. Choose a sandbox key when trying out payment workflows.",
    docs: "https://docs.stripe.com/mcp",
    keyUrl: "https://dashboard.stripe.com/apikeys",
  },
  {
    id: "sentry",
    name: "Sentry",
    monogram: "S",
    color: "#553362",
    category: "Development",
    description: "Investigate errors, traces, and application issues.",
    url: "https://mcp.sentry.dev/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.sentry.dev"],
    docs: "https://github.com/getsentry/sentry-mcp",
  },
  {
    id: "supabase",
    name: "Supabase",
    monogram: "S",
    color: "#177454",
    category: "Development",
    description:
      "Explore your database, inspect projects, and manage development.",
    url: "https://mcp.supabase.com/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.supabase.com", "api.supabase.com"],
    confidential: true,
    hint: "Choose the organization and projects you want to share on Supabase’s authorization screen.",
    docs: "https://supabase.com/docs/guides/ai-tools/mcp",
  },
  {
    id: "context7",
    name: "Context7",
    monogram: "C7",
    color: "#146943",
    category: "Documentation",
    description: "Up-to-date library documentation and code examples.",
    url: "https://mcp.context7.com/mcp",
    auth: ["none", "secret"],
    keyLabel: "Context7 API key",
    hint: "Works without an account at a limited rate. Add an API key for higher limits.",
    docs: "https://context7.com/docs/resources/all-clients",
    keyUrl: "https://context7.com/dashboard",
  },
  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    monogram: "M",
    color: "#1169a3",
    category: "Documentation",
    description: "Official Microsoft, Azure, and developer documentation.",
    url: "https://learn.microsoft.com/api/mcp",
    auth: ["none"],
    docs: "https://learn.microsoft.com/en-us/training/support/mcp",
  },
  {
    id: "cloudflare-docs",
    name: "Cloudflare Docs",
    monogram: "CF",
    color: "#a44500",
    category: "Documentation",
    description: "Find answers in Cloudflare’s official documentation.",
    url: "https://docs.mcp.cloudflare.com/mcp",
    auth: ["none"],
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
  },
  {
    id: "clickup",
    name: "ClickUp",
    monogram: "CU",
    color: "#6653d9",
    category: "Work & knowledge",
    description: "Manage tasks, docs, time tracking, and team updates.",
    url: "https://mcp.clickup.com/mcp",
    docs: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
    auth: ["oauth"],
    oauthHosts: ["mcp.clickup.com"],
    scope: "read write",
  },
  {
    id: "monday",
    name: "monday.com",
    monogram: "M",
    color: "#6756c7",
    category: "Work & knowledge",
    description: "Work with boards, projects, and team workflows.",
    url: "https://mcp.monday.com/mcp",
    docs: "https://developer.monday.com/api-reference/docs/build-on-monday-with-ai",
    auth: ["secret"],
    keyLabel: "monday.com API token",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
  },
  {
    id: "todoist",
    name: "Todoist",
    monogram: "T",
    color: "#bf3831",
    category: "Work & knowledge",
    description: "Organize tasks, projects, due dates, and priorities.",
    url: "https://ai.todoist.net/mcp",
    docs: "https://developer.todoist.com/",
    auth: ["oauth"],
    oauthHosts: ["ai.todoist.net", "todoist.com"],
    scope: "data:read_write",
  },
  {
    id: "airtable",
    name: "Airtable",
    monogram: "AT",
    color: "#ad5316",
    category: "Work & knowledge",
    description: "Search bases and work with structured business records.",
    url: "https://mcp.airtable.com/mcp",
    docs: "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
    auth: ["secret"],
    keyLabel: "Airtable personal access token",
    keyHint:
      "Choose a token with access to the bases and actions your ducks need.",
  },
  {
    id: "figma",
    name: "Figma",
    monogram: "F",
    color: "#8a3cd1",
    category: "Design & websites",
    description: "Read design context and work with Figma files.",
    url: "https://mcp.figma.com/mcp",
    docs: "https://developers.figma.com/docs/figma-mcp-server/remote-server-installation/",
    auth: ["oauth"],
    oauthHosts: ["mcp.figma.com", "api.figma.com", "www.figma.com"],
    scope: "mcp:connect",
    confidential: true,
    hint: "Available tools depend on your Figma seat and file permissions.",
  },
  {
    id: "miro",
    name: "Miro",
    monogram: "MI",
    color: "#8a6915",
    category: "Design & websites",
    description: "Explore whiteboards, create diagrams, and organize ideas.",
    url: "https://mcp.miro.com/",
    docs: "https://developers.miro.com/docs/miro-mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.miro.com"],
    scope: "boards:read boards:write openid email",
    confidential: true,
  },
  {
    id: "wix",
    name: "Wix",
    monogram: "W",
    color: "#24292f",
    category: "Design & websites",
    description: "Build and manage Wix sites and business applications.",
    url: "https://mcp.wix.com/mcp",
    docs: "https://www.wix.com/studio/developers/mcp-server",
    auth: ["oauth"],
    oauthHosts: ["mcp.wix.com"],
    scope: "offline_access",
  },
  {
    id: "intercom",
    name: "Intercom",
    monogram: "IC",
    color: "#265ccc",
    category: "Business",
    description: "Find support conversations and customer information.",
    url: "https://mcp.intercom.com/mcp",
    docs: "https://developers.intercom.com/docs/guides/mcp",
    auth: ["secret"],
    keyLabel: "Intercom access token",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
    hint: "Currently available for US-hosted Intercom workspaces.",
  },
  {
    id: "square",
    name: "Square",
    monogram: "SQ",
    color: "#292929",
    category: "Business",
    description: "Work with customers, orders, and your product catalog.",
    url: "https://mcp.squareup.com/mcp",
    docs: "https://developer.squareup.com/docs/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.squareup.com"],
    hint: "Square’s hosted MCP connects to your live account.",
  },
  {
    id: "resend",
    name: "Resend",
    monogram: "R",
    color: "#292929",
    category: "Business",
    description: "Manage email, contacts, templates, and delivery information.",
    url: "https://mcp.resend.com/mcp",
    docs: "https://resend.com/changelog/remote-mcp-server",
    auth: ["secret"],
    keyLabel: "Resend API key",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    monogram: "FC",
    color: "#ae480e",
    category: "Research & search",
    description: "Search websites and extract content for research.",
    url: "https://mcp.firecrawl.dev/v2/mcp",
    docs: "https://docs.firecrawl.dev/mcp-server",
    auth: ["secret"],
    keyLabel: "Firecrawl API key",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
  },
  {
    id: "tavily",
    name: "Tavily",
    monogram: "TV",
    color: "#276db0",
    category: "Research & search",
    description: "Search the web, explore websites, and gather research.",
    url: "https://mcp.tavily.com/mcp/",
    docs: "https://docs.tavily.com/documentation/mcp",
    auth: ["oauth"],
    oauthHosts: ["mcp.tavily.com"],
    scope: "openid offline_access",
  },
  {
    id: "exa",
    name: "Exa",
    monogram: "EX",
    color: "#3445ba",
    category: "Research & search",
    description: "Search the web and find useful company and research sources.",
    url: "https://mcp.exa.ai/mcp",
    docs: "https://exa.ai/docs/get-started/exa-mcp",
    auth: ["none"],
    hint: "Uses Exa’s limited free search access. Authenticated research-agent tools are not included.",
  },
  {
    id: "apify",
    name: "Apify",
    monogram: "AP",
    color: "#8d6318",
    category: "Automation",
    description: "Discover and run web-data collection tools and read results.",
    url: "https://mcp.apify.com",
    docs: "https://docs.apify.com/integrations/mcp",
    auth: ["secret"],
    keyLabel: "Apify API token",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
  },
  {
    id: "make",
    name: "Make",
    monogram: "MK",
    color: "#7435aa",
    category: "Automation",
    description: "Run automation scenarios and manage your Make account.",
    url: "https://mcp.make.com",
    docs: "https://developers.make.com/mcp-server",
    auth: ["oauth"],
    oauthHosts: ["mcp.make.com", "www.make.com"],
    confidential: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    monogram: "GL",
    color: "#ac4a14",
    category: "Development",
    description:
      "Explore repositories, manage issues, and review development work.",
    url: "https://gitlab.com/api/v4/mcp",
    docs: "https://docs.gitlab.com/user/model_context_protocol/mcp_server/",
    auth: ["oauth"],
    oauthHosts: ["gitlab.com"],
    scope: "mcp",
    confidential: true,
    hint: "Connects to GitLab.com. Tools depend on your account and project permissions.",
  },
  {
    id: "cloudflare-platform",
    name: "Cloudflare Platform",
    monogram: "CF",
    color: "#a44500",
    category: "Development",
    description: "Manage Cloudflare infrastructure with scoped account access.",
    url: "https://mcp.cloudflare.com/mcp",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
    auth: ["secret"],
    keyLabel: "Cloudflare API token",
    keyHint:
      "Choose a scoped token with only the account permissions your ducks need.",
  },
  {
    id: "neon",
    name: "Neon",
    monogram: "NE",
    color: "#14704d",
    category: "Development",
    description: "Explore Postgres projects and manage development databases.",
    url: "https://mcp.neon.tech/mcp",
    docs: "https://neon.com/guides/neon-mcp-server-github-copilot-vs-code",
    auth: ["secret"],
    keyLabel: "Neon API key",
    keyHint:
      "Paste the token value without the Bearer prefix. It is encrypted when saved.",
    hint: "Neon recommends its MCP server for development and testing.",
  },
  {
    id: "posthog",
    name: "PostHog",
    monogram: "PH",
    color: "#8f5417",
    category: "Analytics & data",
    description: "Explore product analytics, errors, and feature flags.",
    url: "https://mcp.posthog.com/mcp",
    docs: "https://posthog.com/docs/model-context-protocol",
    auth: ["oauth"],
    oauthHosts: ["mcp.posthog.com", "oauth.posthog.com"],
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    monogram: "HF",
    color: "#8f6c14",
    category: "Analytics & data",
    description: "Find AI models, datasets, papers, and community tools.",
    url: "https://huggingface.co/mcp",
    docs: "https://huggingface.co/docs/hub/agents-mcp",
    auth: ["none", "secret"],
    keyLabel: "Hugging Face access token",
    hint: "Public search works without a token. Add a token for your account’s tools and private resources.",
  },
];
// Only directly connectable hosted services belong in this catalog.
export const mcpSetupGuides = [];
export const catalogProvider = (id) => mcpCatalog.find((p) => p.id === id);
